config/routes.rb
Keks::Application.routes.draw do
  resources :password_resets

  match "dot/:sha256.png", to: "dot#simple", :as => "render_dot", :via => :get
  match "preview", to: "latex#complex", :as => "render_preview", :via => :post

  root :to => "main#overview"

  get "main/overview"
  match "hitme", as: "main_hitme", to: "main#hitme"
  match "help", as: "main_help", to: "main#help"

  resources :users, except: :index
  match "users/:id/enrollment" => "users#enroll", as: "enroll_user", via: :post
  match "users/:id/starred" => "users#starred", as: "starred", via: :get
  match "users/:id/history" => "users#history", as: "history", via: :get
  match "questions/:id/star" => "questions#star", as: "star_question", via: :get
  match "questions/:id/unstar" => "questions#unstar", as: "unstar_question", via: :get
  match "questions/:id/perma" => "questions#perma", as: "perma_question", via: :get
  match "stats/:question_id" => "stats#new", as: "new_stat", via: :post

  get "admin/overview"
  scope "/admin" do
    resources :text_storage, only: :update

    match "users", to: "users#index", as: "user_index", via: :get
    match "users/:id/reviews", to: "users#reviews", as: "user_reviews", via: :get
    match "toggle_reviewer/:id", to: "users#toggle_reviewer", as: "user_toggle_reviewer", via: :put
    match "toggle_admin/:id", to: "users#toggle_admin", as: "user_toggle_admin", via: :put

    match "reviews", to: "reviews#messages", as: "reviews", via: :get

    match "reviews/need_attention", to: "reviews#need_attention", as: "need_attention_questions", via: :get

    match "reviews/filter/:filter", to: "reviews#filter", as: "review_filter",via: :get
    match "reviews/find_next/:filter/", to: "reviews#find_next", as: "review_find_next",via: :get
    match "reviews/find_next/:filter/:next", to: "reviews#find_next", as: "review_find_next",via: :get

    resources :questions do
      resources :answers
      resources :hints
      match "toggle_release", to: "questions#toggle_release", as: "toggle_release", via: :put
      match "overwrite_reviews", to: "questions#overwrite_reviews", as: "overwrite_reviews", via: :put
      match "review", to: "reviews#review", as: "review", via: :get
      match "review", to: "reviews#save", as: "review_save", via: :post # new reviews
      match "copy", to: "questions#copy", as: "copy", via: :get
      match "copy_to", to: "questions#copy_to", as: "copy_to", via: :post
      get "list_cat/:category_id", to: "questions#list_cat", on: :collection, as: "list_cat"
      get "select", to: "questions#select", on: :collection, as: "select"
      get :search, on: :collection
    end

    match "single_parent_select", to: "questions#single_parent_select", as: "single_parent_select", via: :get

    resources :categories do
      get "index_details/:category_ids", to: "categories#index_details", on: :collection, as: "index_details"
    end
    match "categories/:id/release", to: "categories#release", :as => "release_category", via: :get
    match "suspicious_assocations", to: "categories#suspicious_associations", :as => "suspicious_associations", via: :get
    match "categories_listmove", to: "categories#listmove", :as => "categories_listmove", via: :get
    match "categories_move", to: "categories#move", :as => "categories_move", via: :get
    match "categories_listactivate", to: "categories#listactivate", :as => "categories_listactivate", via: :get
    match "categories_listdeactivate", to: "categories#listdeactivate", :as => "categories_listdeactivate", via: :get
    match "categories_activate", to: "categories#activate", :as => "categories_activate", via: :get
    match "categories_deactivate", to: "categories#deactivate", :as => "categories_deactivate", via: :get
    match "category_report", to: "stats#category_report", :as => "stat_category_report", via: :get
    match "activity_report", to: "stats#activity_report", :as => "stat_activity_report", via: :get
    match "report/:enrollment_key", to: "stats#report", :as => "stat_report", via: :get

    match "tree", to: "admin#tree", :as => "tree", via: :get
    match "export", to: "admin#export", :as => "export", via: :get
    match "export_question/:question_id", to: "admin#export_question", :as => "export_question", via: :get
  end

  match "main/questions", to: "main#questions", :as => "main_question", via: :get
  match "main/single_question", to: "main#single_question", :as => "main_single_question", via: :get
  match "main/multiple_question", to: "main#multiple_question", :as => "main_multiple_question", via: :get
  match "feedback", to: "main#feedback", :as => "feedback", via: :get
  match "feedback_send", to: "main#feedback_send", :as => "feedback_send", via: :post
  match "random_xkcd", to: "main#random_xkcd", :as => "random_xkcd", via: :get
  match "specific_xkcd/:id", to: "main#specific_xkcd", :as => "specific_xkcd", via: :get

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  match '/perf', to: 'perfs#create', via: :post

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:show]
    end
  end

end

app/models/answer.rb
# encoding: utf-8

class Answer < ActiveRecord::Base
  attr_accessible :correct, :text

  validates :text, :uniqueness => { :scope => :question_id,
    :message => "Es gibt bereits eine Antwort mit genau dem gleichen Text zu dieser Frage." }

  belongs_to :question, inverse_of: :answers, touch: :content_changed_at, counter_cache: true
  alias_method :parent, :question

  # i.e. this answer has many questions and acts as parent to them
  has_many :questions, :as => :parent
  attr_readonly :questions_count

  has_many :stats

  has_and_belongs_to_many :categories


  after_save { self.question.index! }
  after_destroy { self.question.index! }

  before_save do
    Rails.cache.write(:answers_last_update, Time.now)

    up = text_changed? || correct_changed?
    self.question.update_attribute('content_changed_at', Time.now) if up
  end

  include TraversalTools

  def check_ratio
    return -1 if question.matrix_validate?
    all = question.stats.pluck(:selected_answers).flatten
    me = all - [id]
    return 1-me.size.to_f/all.size.to_f
  end


  def get_all_subquestions
    questions + categories.map { |c| c.questions }.flatten
  end

  def released?
    question.released?
  end


  def link_text
    "Antwort #{link_text_short}"
  end

  def link_text_short
    "#{question.ident}/A#{id}"
  end

  include DotTools

  def dot
    txt = 'A: ' + id.to_s
    %(#{dot_id} [label="#{txt}", shape=hexagon, color=#{correct? ? 'green' : 'red'}];\n)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def show
    @qs = Question.includes(:answers).find(params[:id])

    render json: @qs.as_json(:only => [:text], include: { answers: {:only => [:text, :correct]}})
  end
end

app/controllers/questions_controller.rb
# encoding: utf-8

class QuestionsController < ApplicationController
  before_filter :require_admin, except: [:star, :unstar, :perma]
  before_filter :signed_in_user, only: [:star, :unstar]
  before_filter :find_question, only: [:copy, :copy_to, :star, :unstar, :edit, :show, :perma, :toggle_release, :update, :destroy]
  before_filter :expires_now, only: [:star, :unstar]

  before_filter :def_etag, only: [:index, :list_cat, :perma, :edit, :show]

  def copy
    render partial: 'copy' if stale?(etag: etag)
  end

  def copy_to
    def abort(msg)
      flash[:error] = msg
      redirect_to @question
    end

    ident = params[:ident].strip rescue ""
    if ident.blank?
      return abort("Kein Ident angegeben, daher kann die Frage nicht kopiert werden.")
    end

    if Question.where(ident: ident).any?
      return abort("Der angegebene Ident „#{ident}“ wird bereits verwendet. Kopieren fehlgeschlagen.")
    end

    new_question = @question.dup
    new_question.ident = ident
    new_question.released = false

    if new_question.save
      flash[:success] = "Frage kopiert. Du musst die Frage erst freigeben, bevor sie den Studis angezeigt wird."
    else
      return abort("Ein interner Fehler ist aufgetreten und die Frage konnte nicht kopiert werden. Details in den Logs.")
    end

    copy_assoc_objects(new_question)

    redirect_to question_path(new_question)
  end

  def star
    return render(json: "keine Frage") if !@question
    begin
      current_user.starred << @question
    rescue; end unless current_user.has_starred?(@question)
    render :json => current_user.has_starred?(@question)
  end

  def unstar
    return render(json: false) if !@question
    current_user.starred.delete(@question)
    render :json => current_user.has_starred?(@question)
  end

  def index
    @categories = Category.with_questions.order(:title).all
  end

  def list_cat
    @questions = if params[:category_id] == "-1"
      Question.where("parent_type = ? OR parent_id = ?", "Answer", nil)
    else
      Question.with_parent_cat(params[:category_id])
    end

    ActiveRecord::lax_includes do
      @questions = @questions.includes(parent: :question).all
    end

    render partial: "index_table"
  end

  def search
    @page = page = [params[:page].to_i, 1].max

    return unless stale?(etag: etag("#{@page}__#{params[:query]}"))

    @search = Question.search do
      fulltext(params[:query]) do
        highlight :ident, :text, :answers, :reviews, :hints, :parent
        query_phrase_slop 2
        boost_fields ident: 2.0
        boost_fields text: 1.5
        boost_fields answers: 1.1
        phrase_slop 2
      end
      paginate page: page, per_page: 30
    end
    @questions = @search.results
  end

  def select
    ids = params['question_ids']*","
    
    redirect_to main_hitme_url + "#hide-options" + "#hide-categories" + "#question=" + ids
  end

  def new
    @question = Question.new

    if params['parent']
      s = params['parent'].split('_', 2)

      @answer = Answer.find(s.last.to_i) if s.first == "Answer"
      @question.parent = @answer if @answer

      @category = Category.find(s.last.to_i) if s.first == "Category"
      @question.parent = @category if @category
    end
  end

  def edit
  end

  def show
    @question = Question.includes(:reviews, answers: [:questions, :categories]).find(params[:id])
  end

  def perma
  end

  def toggle_release
    if @question.toggle(:released) && @question.save
      flash[:success] = "Frage aktualisiert (Released: #{@question.released})"
      redirect_to :back
    else
      flash[:error] = "Konnte den Release-Status der Frage nicht umschalten."
      render 'edit'
    end
  end

  def overwrite_reviews
    @question = Question.includes(:reviews).find(params[:question_id])
    time = Time.now.strftime("%Y-%m-%d %H:%M")
    okay = true
    @question.reviews.each do |r|
      if r.okay?
        r.touch if r.question_updated_since?
      else
        r.okay = true
        r.comment = "#{time}: von #{current_user.nick} auf „okay“ gestellt\n\n#{r.comment}".strip
        okay = false unless r.save
      end
    end

    if okay
      flash[:success] = "Alle Reviews sollten jetzt „okay“ sein."
    else
      flash[:error] = "Es ist ein Fehler aufgetreten. Prüfe den Status der Reviews manuell."
    end

    redirect_to question_review_path(@question)
  end

  def update
    begin
      p = params[:parent].split('_')
      p = (p[0] == "Category") ? Category.find(p[1]) : Answer.find(p[1])
    rescue
      flash[:error] = "Kein gültiges Elter-Element angegeben"
      return render 'edit'
    end
    @question.parent = p

    if @question.update_attributes(params[:question])
      flash[:success] = "Frage aktualisiert"
      redirect_to @question
    else
      render 'edit'
    end
  end

  def single_parent_select
    render partial: "form_single_parent_select"
  end


  def create
    @question = Question.new(params[:question])

    begin
      p = params[:parent].split('_')
    rescue
      flash[:error] = "Kein gültiges Elter-Element angegeben"
      return render 'new'
    end

    p = (p[0] == "Category") ? Category.find(p[1]) : Answer.find(p[1])
    @question.parent = p

    if @question.save
      flash[:success] = "Frage gespeichert"
      redirect_to @question
    else
      render 'new'
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = "Frage gelöscht"
    else
      flash[:error] = "Frage nicht gelöscht. Siehe Log für mehr Informationen."
    end
    redirect_to questions_path
  end

  private
  def find_question
#    id = params[:question_id] ? params[:question_id] : params[:id]
    id = params[:question_id] ? params[:question_id] : params[:question_ids] ? params[:question_ids] : params[:id]
    @question = Question.find(id)
  end

  # copies answers and hints from this question to the specified one if
  # enabled. The status is directly read from the post parameters.
  def copy_assoc_objects(question)
    objs = []
    objs += @question.answers if params[:copy_answers] == "1"
    objs += @question.hints if params[:copy_hints] == "1"

    all_ok = true
    objs.each do |o|
      new_obj = o.dup
      new_obj.question = question
      all_ok = false unless new_obj.save
    end

    unless all_ok
      flash[:warning] = "Nicht alle Antworten/Hinweise konnten kopiert werden. Details in den Logs."
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def link_to_parent(q)
    return "Kein Eltern-Elem." if q.nil? || q.parent.nil?
    if q.parent.is_a?(Category)
      link_to(q.parent.link_text, q.parent)
    else
      link_to(q.parent.link_text, q.parent.question)
    end
  end

  def get_question_stat_counts(questions = nil)
    filter = {}

    if questions
      questions = [questions] unless questions.is_a?(Array)
      quest_ids = questions.map { |q| q.is_a?(Question) ? q.id : q.to_i }
      filter = {question_id: quest_ids}
    end

    s = Stat.unscoped.where(filter)

    {
      all:     s.group(:question_id).count,
      skip:    s.where(skipped: true).group(:question_id).count,
      correct: s.where(correct: true).group(:question_id).count
    }
  end

  def get_answer_stat_counts(question)
    counts = {}
    stats = Stat.unscoped.where(question_id: question.id).pluck(:selected_answers)
    stats.flatten.group_by { |i| i}.each { |answ_id, v| counts[answ_id] = v.size }
    counts[:all] = counts.values.reduce(:+)
    counts
  end
end

app/views/questions/_action_menu.html.erb
<ul class="button-group">
  <li><%= link_to "Diese Frage Bearbeiten", edit_question_path(@question), class: 'button' %></li>
  <li><%= link_to "Reviews (#{@question.reviews.size})", question_review_path(@question), class: 'button' %></li>
  <li><%=link_to "Weitere Antwort", new_question_answer_path(@question), class: "button" %></li>
  <li><%=link_to "Weiterer Hinweis", new_question_hint_path(@question), class: "button" %></li>
  <li><%=link_to "Kopieren", question_copy_path(@question), class: "button ajax-popup-link" %></li>
  <li><%=link_to "Löschen", question_path(@question), method: :delete, class: "button danger", confirm: "Dies löscht die Frage, alle Hinweise und Antworten. Durch gelöschte Antworten werden Kategorien möglicherweise zu neuen Wurzeln und es ist möglich, dass Fragen in der Luft hängen.\n\nFortfahren?" %></li>
</ul>

app/views/questions/_copy.html.erb
<h2>Frage <%=@question.ident%> kopieren</h2>
<%= form_tag(question_copy_to_path(@question), method: :post) do %>
  <%= label_tag :ident %>
  <%= text_field_tag :ident %>
  <span>Benötigt. Muss eindeutig sein bzgl. aller Fragen.</span>

  <% if @question.answers.any? %>
    <%= label_tag :copy_answers, "Antworten kopieren" %>
    <%= check_box_tag :copy_answers, 1, true %>
  <% end %>

  <% if @question.hints.any? %>
    <%= label_tag :copy_hints, "Hinweise kopieren" %>
    <%= check_box_tag :copy_hints, 1, true %>
  <% end %>

  <hr class="clear"/>
  <div class="button-group">
    <%= submit_tag "Kopieren", class: "button primary", disable_with: "Bitte warten…" %>
    <%= link_to "Abbrechen", @question, class: "button", data: { action: "close-popup" } %>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :ident %>
  <%= f.text_field :ident %>
  <span>Benötigt. Muss eindeutig sein bzgl. aller Fragen.</span>

  <%= f.label :text %>
  <%= f.text_area :text, "data-preview" => "#preview"  %>
  <span>Benötigt<%=render "latex/help"%></span>
  <div id="preview"><%= render_tex(@question.text) %></div>

  <%#= render "form_single_parent_select", f: f %>

  <%= f.label :parent, "Elter" %>
  <% if @question.parent %>
    <div style="float:left">
      <input type="hidden" name="parent" value="<%=@question.parent_html_ref%>"/>
      <%=@question.parent.link_text%>
      <a data-replace-parent-url="<%=single_parent_select_path(parent: @question.parent_html_ref)%>" data-disable-with="…lädt…">(anderes Eltern-Element wählen?)</a>
    </div>
  <% else %>
    <%= render "form_single_parent_select" %>
  <% end %>

  <%= f.label :difficulty, "Fragentyp" %>
  <%= f.select :difficulty, Difficulty.to_select %>

  <%= f.label :study_path %>
  <%= f.select :study_path, StudyPath.to_select %>
  <span>(Diese Frage ist gedacht für…)</span>

  <%#= f.label :video_link %>
  <%#= f.text_field :video_link   %>

  <%= f.label :released %>
  <%= f.check_box :released %>

  <%= f.submit @question.new_record? ? "Frage anlegen" : "Speichern", class: "button primary big" %>

  <br class="clear"/>
  <%= link_to("Zurück zur Kategorie", @category) if @category %>
  <%= link_to("Zurück zur Frage", @anwer.question) if @anwer %>
<% end %>

app/views/questions/_form_single_parent_select.html.erb
<select name="parent" class="comboxbox">
  <option></option>
  <optgroup label="Antworten">
    <% Answer.joins(:question).select("answers.id, questions.ident AS quest_ident").order("answers.id").each do |a| %>
      <% v = "Answer_#{a.id}" %>
      <%= content_tag(:option, "#{a.quest_ident}/A#{a.id}", value: v, selected: params[:parent] == v) %>
    <% end %>
  </optgroup>
  <optgroup label="Kategorien">
    <% Category.order(:ident).select([:id, :ident]).each do |c| %>
      <% v = "Category_#{c.id}" %>
      <%= content_tag(:option, c.ident, value: v, selected: params[:parent] == v) %>
    <% end %>
  </optgroup>
</select>
<span>ggf. vorhergehende Fragen und Kategorien zuerst anlegen</span>

app/views/questions/_index_table.html.erb
<table id="index" class="tablesorter tex2jax_ignore">
  <thead>
    <tr>
      <th>Ident<br/>Typ<br/>Studiengang<br/>Elternname</th>
      <th>Text</th>
      <th>%-richtig<br/>%-übersprungen<br/>%-ok? (Review)</th>
      <th>Aktionen</th>
    </tr>
  </thead>
  <tbody>
    <%
      counts = get_question_stat_counts(@questions)
      revs = Review.group(:question_id, :okay).count
    %>
    <% @questions.each do |q| %>
      <tr>
        <td>
          <div style="width: 400px">
            <%=link_to(q.ident, question_path(q), :class => q.complete? ? "" : "strike")%><%=q.incomplete_reason%><br/>
            <%=q.difficulty(:name) %><br/>
            <%=q.study_path(:name) %><br/>
            <%=link_to_parent(q)%>
          </div>
        </td>
        <td>
          <div style="width: 350px; max-height: 120px; overflow: hidden;">
            <%# heuristic, more text would probably be cut off anyway %>
            <%= q.text[0..300]  %>
          </div>
        </td>
        <td>
          ✓&nbsp;<%=perc(counts[:correct][q.id], counts[:all][q.id], "nie beantwortet") %><br/>
          ↷&nbsp;<%=perc(counts[:skip][q.id], counts[:all][q.id], "nie beantwortet")%><br/>
          ☯&nbsp;<%=perc(revs[[q.id, true]], (revs[[q.id, true]] || 0) + (revs[[q.id, false]] || 0), "keine Reviews")%><br/>
        </td>
        <td>
          <%= link_to "Anzeigen", question_path(q) %><br/>
          <%= link_to "Bearbeiten", edit_question_path(q) %><br/>
          <%= link_to "Neue Antwort", new_question_answer_path(q) %><br/>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/_render.html.erb
<h3 class="count">Frage</h3>

<%=render_tex(question.text)%>

app/views/questions/_render_full.html.erb
<div>
  <% if defined?(show_question_id) && show_question_id %>
    <h3>Frage <%= q.id %></h3>
  <% else %>
    <h3 class="count">Frage</h3>
  <% end %>
  <% if signed_in? %>
  <script>
    document.write(renderStarred({id: <%=q.id%>,
      starred: <%=q.starred_by.include?(current_user) ? "true" : "false"%>}
    ));
  </script>
  <% end %>
  <%=render_tex q.text %>
  <br/>
  <% if q.matrix_validate? %>
    <strong>Antwort:</strong> Hier wäre das Ergebnis in ein Textfeld einzutragen.
  <% else %>
    <strong>Antwortmöglichkeiten:</strong>
    <ul style="margin-top: 10px;margin-bottom:0">
      <% q.answers.each do |a| %>
        <li><%=render_tex a.text %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/questions/_render_review.html.erb
<% cache("question/render_review/#{@question.id}/#{@question.content_changed_at}") do %>
<%=render_tex(@question.text)%><br/><br/>

<% if question.hints.any? %>
   <strong>Hinweise:</strong>
  <ol>
  <% question.hints.each do |h| %>
    <li><%=render_tex(h.text)%></li>
  <% end %>
  </ol><br/>
<% end %>

<% if question.matrix_validate? %>
  <strong>Lösung:</strong><br/>
  <%=render_tex question.answers.first.text %>
<% else %>
  <strong>Antwortmöglichkeiten:</strong>
  <table class="evenodd spaced">
    <tr><th></th><th>Text</th><th>Verweise / Subfragen</th></tr>
    <%  question.answers.each do |a| %>
      <tr>
        <td><%=render_correctness(a)%></td>
        <td><%=render_tex a.text%></td>
        <td>
          <% a.questions.each do |q| %>
            <%= link_to q.ident, question_review_path(q) %>
          <% end %>
          <% a.categories.each do |c| %>
            {<%= c %>:
            <% c.questions.each do |q| %>
              <%= link_to q.ident, question_review_path(q) %>
            <% end %>
            }
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<% end %>

app/views/questions/edit.html.erb
<% provide(:title, "Frage bearbeiten: #{@question.ident}") %>

<%= render "admin/action_menu" %>

<div>

  <h2>Frage bearbeiten</h2>

  <%= render "form" %>

  <br/>
  <%= link_to "Zurück zur Frage", @question %><br/>
  <%= link_to "Zurück zu den Reviews", question_review_path(@question) %><br/>
  <%= link_to "Zurück zur Fragenliste", questions_path %>
</div>

app/views/questions/index.html.erb
<% provide(:title, "Fragenliste") %>

<%= render "admin/action_menu" %>

<div>
  Es werden nur Kategorien mit Fragen angezeigt. Eine aufgeklappte Kategorie enthält <em>nur direkte Fragen</em>, d.h. Subfragen werden nicht berücksichtigt. Stattdessen erscheinen diese unter „Subfragen oder Fragen ohne Elter“.
</div>

<div>
  <h2>Subfragen oder Fragen ohne Elter</h2>
  <div class="toggle search-content-urls" style="display: none">
    <div data-content-url="<%=list_cat_questions_path(category_id: "-1")%>">…lädt…</div>
  </div>
</div>


<% @categories.group_by { |c| c.title.split(":").first }.each do |group_title, cats| %>
<div>
  <% if cats.size == 1 %>
    <h2><%= cats.first.title %> <small>(<%=cats.first.questions_count%> Fragen)</small></h2>
      <div class="toggle search-content-urls" style="display: none">
        <div data-content-url="<%=list_cat_questions_path(category_id: cats.first.id)%>">…lädt…</div>
    </div>
  <% else %>
    <h2><%=group_title%></h2>
    <% cats.each do |c| %>
      <h3><%= c.title.split(":").last %> <small>(<%=c.questions_count%> Fragen)</small></h3>
      <div class="toggle search-content-urls" style="display: none">
        <div data-content-url="<%=list_cat_questions_path(category_id: c.id)%>">…lädt…</div>
      </div>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/questions/new.html.erb
<% provide(:title, "Neue Frage hinzufügen") %>

<%= render "admin/action_menu" %>

<div>

  <h2>Neue Frage</h2>

  <%= render "form" %>
</div>

app/views/questions/search.html.erb
 <% provide(:title, "Fragen suchen") %>

<%= render "admin/action_menu" %>

<div>

  <h2>Fragen: Suchen</h2>

  <%= form_tag search_questions_path, method: :get, class: "search", autocomplete: "off", data: { ajax: 1, "extract-selector" => "#wrapper", "target-selector" => "#results", "update-url" => 1 } do %>
    <ul class="button-group">
      <li><%= text_field_tag :query, params[:query], placeholder: %|Suchbegriffe| %></li>
      <li><%= submit_tag "Suchen", name: nil, class: "button primary" %></li>
      <li><%= link_to "Alle Fragen", search_questions_path, class: "button" %></li>
      <li><%= link_to "gigantische Liste", questions_path, class: "button", confirm: "Dies wird alle Fragen am Stück auflisten. Das ist langsam. Fortfahren?" %></li>
    </ul>
  <% end %>

  <div id="results" class="tex2jax_ignore"><div id="wrapper">
    <div class="pagination">
      <div class="info"><%= page_entries_info @questions %></div>
      <%= will_paginate @questions, container: false, params: { query: params[:query] } %>
    </div>

    <%= form_tag select_questions_path, :method => :get do %>
    <table style="width:100%">
      <% @search.hits.each do |hit| %>
        <tr>
          <td><%= check_box_tag "question_ids[]", hit.primary_key %></td>
          <td>
          <%= link_to search_highlight(hit, :ident, true), question_path(hit.primary_key) %><br/>
          <%=
            snip = [:text, :answers, :hints, :reviews, :parent].map do |f|
              search_snippet(hit, f)
            end.join
            raw snip.blank? ? search_snippet(hit, :text, true) : snip
          %>
          </td>
        </tr>
      <% end %>
      <tr><td colspan="2"><%= submit_tag "Select" %></td></tr>
    <% end %>
    </table>

    <div class="pagination">
      <%= will_paginate @questions, container: false, params: { query: params[:query] } %>
      <div class="info"><%= page_entries_info @questions %></div>
    </div>

  </div></div>
</div>

app/views/questions/select.html.erb
<% provide(:title, "Fragen beantworten") %>

<% @questions.each do |hit| %>
<% provide(:title, "Frage #{hit.id}") %>

<div>
  <%= render "questions/render_full", q: hit, show_question_id: true %>
  <br/><br/>
  <%=link_to "Diese Frage jetzt beantworten", "#{main_hitme_path}#hide-options#question=#{hit.id}" %>
</div>
<% end %>

app/views/questions/tree.html.erb
<h1>Question#tree</h1>
<p>Find me in app/views/question/tree.html.erb</p>