config/routes.rb
Keks::Application.routes.draw do
  resources :password_resets

  match "dot/:sha256.png", to: "dot#simple", :as => "render_dot", :via => :get
  match "preview", to: "latex#complex", :as => "render_preview", :via => :post

  root :to => "main#overview"

  get "main/overview"
  match "hitme", as: "main_hitme", to: "main#hitme"
  match "help", as: "main_help", to: "main#help"

  resources :users, except: :index
  match "users/:id/enrollment" => "users#enroll", as: "enroll_user", via: :post
  match "users/:id/starred" => "users#starred", as: "starred", via: :get
  match "users/:id/history" => "users#history", as: "history", via: :get
  match "questions/:id/star" => "questions#star", as: "star_question", via: :get
  match "questions/:id/unstar" => "questions#unstar", as: "unstar_question", via: :get
  match "questions/:id/perma" => "questions#perma", as: "perma_question", via: :get
  match "stats/:question_id" => "stats#new", as: "new_stat", via: :post

  get "admin/overview"
  scope "/admin" do
    resources :text_storage, only: :update

    match "users", to: "users#index", as: "user_index", via: :get
    match "users/:id/reviews", to: "users#reviews", as: "user_reviews", via: :get
    match "toggle_reviewer/:id", to: "users#toggle_reviewer", as: "user_toggle_reviewer", via: :put
    match "toggle_admin/:id", to: "users#toggle_admin", as: "user_toggle_admin", via: :put

    match "reviews", to: "reviews#messages", as: "reviews", via: :get

    match "reviews/need_attention", to: "reviews#need_attention", as: "need_attention_questions", via: :get

    match "reviews/filter/:filter", to: "reviews#filter", as: "review_filter",via: :get
    match "reviews/find_next/:filter/", to: "reviews#find_next", as: "review_find_next",via: :get
    match "reviews/find_next/:filter/:next", to: "reviews#find_next", as: "review_find_next",via: :get

    resources :questions do
      resources :answers
      resources :hints
      match "toggle_release", to: "questions#toggle_release", as: "toggle_release", via: :put
      match "overwrite_reviews", to: "questions#overwrite_reviews", as: "overwrite_reviews", via: :put
      match "review", to: "reviews#review", as: "review", via: :get
      match "review", to: "reviews#save", as: "review_save", via: :post # new reviews
      match "copy", to: "questions#copy", as: "copy", via: :get
      match "copy_to", to: "questions#copy_to", as: "copy_to", via: :post
      get "list_cat/:category_id", to: "questions#list_cat", on: :collection, as: "list_cat"
      get "select", to: "questions#select", on: :collection, as: "select"
      get :search, on: :collection
    end

    match "single_parent_select", to: "questions#single_parent_select", as: "single_parent_select", via: :get

    resources :categories do
      get "index_details/:category_ids", to: "categories#index_details", on: :collection, as: "index_details"
    end
    match "categories/:id/release", to: "categories#release", :as => "release_category", via: :get
    match "suspicious_assocations", to: "categories#suspicious_associations", :as => "suspicious_associations", via: :get
    match "categories_listmove", to: "categories#listmove", :as => "categories_listmove", via: :get
    match "categories_move", to: "categories#move", :as => "categories_move", via: :get
    match "categories_listactivate", to: "categories#listactivate", :as => "categories_listactivate", via: :get
    match "categories_listdeactivate", to: "categories#listdeactivate", :as => "categories_listdeactivate", via: :get
    match "categories_activate", to: "categories#activate", :as => "categories_activate", via: :get
    match "categories_deactivate", to: "categories#deactivate", :as => "categories_deactivate", via: :get
    match "category_report", to: "stats#category_report", :as => "stat_category_report", via: :get
    match "activity_report", to: "stats#activity_report", :as => "stat_activity_report", via: :get
    match "report/:enrollment_key", to: "stats#report", :as => "stat_report", via: :get

    match "tree", to: "admin#tree", :as => "tree", via: :get
    match "export", to: "admin#export", :as => "export", via: :get
    match "export_question/:question_id", to: "admin#export_question", :as => "export_question", via: :get
  end

  match "main/questions", to: "main#questions", :as => "main_question", via: :get
  match "main/single_question", to: "main#single_question", :as => "main_single_question", via: :get
  match "main/multiple_question", to: "main#multiple_question", :as => "main_multiple_question", via: :get
  match "feedback", to: "main#feedback", :as => "feedback", via: :get
  match "feedback_send", to: "main#feedback_send", :as => "feedback_send", via: :post
  match "random_xkcd", to: "main#random_xkcd", :as => "random_xkcd", via: :get
  match "specific_xkcd/:id", to: "main#specific_xkcd", :as => "specific_xkcd", via: :get

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  match '/perf', to: 'perfs#create', via: :post

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:show]
    end
  end

end

app/views/admin/_action_menu.html.erb
<ul class="submenu box">
  <li>Admin:</li>
  <li><%= link_to "Startseite („dies und das“)", admin_overview_path, class: '' %></li>
  <li><%= link_to "Kategorienliste", categories_path, class: 'primary' %></li>
  <li><%= link_to "Fragen suchen", search_questions_path, class: 'primary' %></li>
  <li><%= link_to "Nutzerliste", user_index_path, class: '' %></li>
  <li><%= link_to "Neue Kategorie", new_category_path, class: '' %></li>
  <li><%= link_to "Neue Frage", new_question_path, class: '' %></li>
</ul>

app/views/admin/_export_question.html.erb
<% cache("admin/export_question/#{question.id}/#{question.content_changed_at}") do %>
<%
  all_sub_q = []
  feedback_text = "Liebes KeKs Team,\n\nbzgl. Frage #{question.ident} möchte ich euch sagen:\n\n\n\nViele Grüße\n\nFrage als Admin ansehen:\n#{question_url(question)}"
%>


<h3>
  <%= question.complete? ? '' : 'UNFERTIGE ' %>
  Frage: <%= question.ident %>
  –– <%= link_to "Feedback zu dieser Frage", feedback_path(text: feedback_text) %>
</h3>

<% @question = question %>
<%= render "questions/render_review", question: question %>

<hr/>


<% question.answers.each { |a| all_sub_q << a.get_all_subquestions }%>
<% all_sub_q = all_sub_q.flatten.uniq#.reject { |q| !q.complete? } %>
<% if all_sub_q.any? && max_depth >= 0 %>
  <% all_sub_q.each do |q| %>
    <div style="padding-left:20px;border-left:1px solid #ddd">
      <%= render 'export_question', question: q, max_depth: (max_depth-1) %>
    </div>
  <% end %>
<% end %>

<% end %>

app/views/admin/export.html.erb
<% provide(:title, "Export") %>

<div>Diese Seite ist für das Review von Fragen gedacht. Fragen die noch nicht fertig sind oder noch nicht freigegeben wurden sind mit einem „UNFERTIG“ versehen. Die Seite ist für Admins und Reviewer (wenn sie den Link kennen) einsehbar.</div>

<% Category.with_questions.is_root.includes(:questions).all.each do |c| %>
  <div>
    <h2><%= c.title %> <small>(<%=c.questions_count%> Fragen)</small></h2>
    <div class="toggle search-content-urls" style="display: none">
    <% c.questions.each do |q| %>
      <div data-content-url="<%=export_question_path(q)%>">…Lade…</div>
    <% end %>
    </div>
  </div>
<% end %>

app/views/admin/overview.html.erb
<% provide(:title, "Admin Übersicht") %>

<%= render "action_menu" %>

<div>
  <h2>Statistiken</h2>

  <%= link_to "Nutzungsstatistik", stat_activity_report_path %><br/>
  <%= link_to "Statistik nach Wurzel-Kategorien", stat_category_report_path %><br/>
  <% EnrollmentKeys.all.each do |id, name| %>
    <%= link_to name, stat_report_path(name) %>
  <% end %>
</div>

<div>
  <h2>Dateneingabe</h2>
  <p>
    <b>Wie funktioniert das?</b><br/>

    Eine Kategorie hat viele Fragen. Eine Frage hat viele Antworten. Eine Antwort verweist auf Kategorien und/oder Fragen. Im Umkehrschluss hat jede Frage <em>genau ein</em> Eltern-Element, nämlich Kategorie ⊕ Antwort. Fehlt dieses Eltern-Element wird die Frage nicht berücksichtigt. Kategorien gehören entweder zu einer Antwort oder haben kein Eltern-Element. Dann sind sie eine Wurzel und werden dem Nutzer am Anfang zur Auswahl angeboten.
  </p>
</div>

<div>
  <h2>Export</h2>
  <p>
    Auf dieser öffentlichen Seite sind alle Fragen aufgelistet, inkl. Antworten und Hinweisen. Jeder große Block ist eine Wurzel-Kategorie, Unterkategorien werden nicht mehr angezeigt. Die Fragen sind aber entsprechend ihrer Tiefe eingerückt. Die Seite ist für jeden der den Link kennt einsehbar.
  </p>

  <%= link_to "Review/Export Seite", export_path %>
</div>

<div>
  <h2>Ein Baum sie zu knechten</h2>
  <p>Du kannst eine vollständige Übersicht aller Kategorien, Fragen, Antworten, Hinweise und deren Verknüpfungen herunterladen. Die Erstellung erfolgt jedes Mal live und dauert daher etwas.</p>

  <h3>als .DOT / Preview mit xdot</h3>
  <p><%=link_to "Download als .DOT", tree_url + ".dot" %> (mit Inkscape öffnen)</p>
  <p>Installiere Dir zuerst <tt>xdot</tt> (etwa <tt>apt-get install xdot</tt>). Danach kannst Du Dir mit folgendem Befehl den Graphen anzeigen lassen und flüssig darin scrollen.<br/><b>Beachte:</b> Der Baum ist riesig, daher siehst Du am Anfang meist gar nichts. Klicke daher zuerst ein paar Mal auf den Zoom-In Button.</p>
  <pre>wget -q -O - <%=tree_url%>.dot | xdot</pre>

  <h3 class="toggle-closed">als .SVGZ / Preview mit evince</h3>
  <div class="toggle" style="display: none">
    <p><%=link_to "Download als .SVGZ", tree_url + ".svgz" %> (mit Inkscape öffnen)</p>
    <p>Auf den meisten Linuxsystemen sollte folgender Befehl den Baum herunterladen und mit Evince anzeigen, sofern Inkscape installiert ist:</p>
    <pre>pushd $TMP \
      && rm -f tree.svgz \
      && wget -q <%=tree_url%>.svgz \
      && inkscape tree.svgz --export-pdf=tree.pdf \
      && evince tree.pdf \
      && rm tree.svgz; \
      popd
    </pre>
  </div>
</div>