config/routes.rb
Keks::Application.routes.draw do
  resources :password_resets

  match "dot/:sha256.png", to: "dot#simple", :as => "render_dot", :via => :get
  match "preview", to: "latex#complex", :as => "render_preview", :via => :post

  root :to => "main#overview"

  get "main/overview"
  match "hitme", as: "main_hitme", to: "main#hitme"
  match "help", as: "main_help", to: "main#help"

  resources :users, except: :index
  match "users/:id/enrollment" => "users#enroll", as: "enroll_user", via: :post
  match "users/:id/starred" => "users#starred", as: "starred", via: :get
  match "users/:id/history" => "users#history", as: "history", via: :get
  match "questions/:id/star" => "questions#star", as: "star_question", via: :get
  match "questions/:id/unstar" => "questions#unstar", as: "unstar_question", via: :get
  match "questions/:id/perma" => "questions#perma", as: "perma_question", via: :get
  match "stats/:question_id" => "stats#new", as: "new_stat", via: :post

  get "admin/overview"
  scope "/admin" do
    resources :text_storage, only: :update

    match "users", to: "users#index", as: "user_index", via: :get
    match "users/:id/reviews", to: "users#reviews", as: "user_reviews", via: :get
    match "toggle_reviewer/:id", to: "users#toggle_reviewer", as: "user_toggle_reviewer", via: :put
    match "toggle_admin/:id", to: "users#toggle_admin", as: "user_toggle_admin", via: :put

    match "reviews", to: "reviews#messages", as: "reviews", via: :get

    match "reviews/need_attention", to: "reviews#need_attention", as: "need_attention_questions", via: :get

    match "reviews/filter/:filter", to: "reviews#filter", as: "review_filter",via: :get
    match "reviews/find_next/:filter/", to: "reviews#find_next", as: "review_find_next",via: :get
    match "reviews/find_next/:filter/:next", to: "reviews#find_next", as: "review_find_next",via: :get

    resources :questions do
      resources :answers
      resources :hints
      match "toggle_release", to: "questions#toggle_release", as: "toggle_release", via: :put
      match "overwrite_reviews", to: "questions#overwrite_reviews", as: "overwrite_reviews", via: :put
      match "review", to: "reviews#review", as: "review", via: :get
      match "review", to: "reviews#save", as: "review_save", via: :post # new reviews
      match "copy", to: "questions#copy", as: "copy", via: :get
      match "copy_to", to: "questions#copy_to", as: "copy_to", via: :post
      get "list_cat/:category_id", to: "questions#list_cat", on: :collection, as: "list_cat"
      get "select", to: "questions#select", on: :collection, as: "select"
      get :search, on: :collection
    end

    match "single_parent_select", to: "questions#single_parent_select", as: "single_parent_select", via: :get

    resources :categories do
      get "index_details/:category_ids", to: "categories#index_details", on: :collection, as: "index_details"
    end
    match "categories/:id/release", to: "categories#release", :as => "release_category", via: :get
    match "suspicious_assocations", to: "categories#suspicious_associations", :as => "suspicious_associations", via: :get
    match "categories_listmove", to: "categories#listmove", :as => "categories_listmove", via: :get
    match "categories_move", to: "categories#move", :as => "categories_move", via: :get
    match "categories_listactivate", to: "categories#listactivate", :as => "categories_listactivate", via: :get
    match "categories_listdeactivate", to: "categories#listdeactivate", :as => "categories_listdeactivate", via: :get
    match "categories_activate", to: "categories#activate", :as => "categories_activate", via: :get
    match "categories_deactivate", to: "categories#deactivate", :as => "categories_deactivate", via: :get
    match "category_report", to: "stats#category_report", :as => "stat_category_report", via: :get
    match "activity_report", to: "stats#activity_report", :as => "stat_activity_report", via: :get
    match "report/:enrollment_key", to: "stats#report", :as => "stat_report", via: :get

    match "tree", to: "admin#tree", :as => "tree", via: :get
    match "export", to: "admin#export", :as => "export", via: :get
    match "export_question/:question_id", to: "admin#export_question", :as => "export_question", via: :get
  end

  match "main/questions", to: "main#questions", :as => "main_question", via: :get
  match "main/single_question", to: "main#single_question", :as => "main_single_question", via: :get
  match "main/multiple_question", to: "main#multiple_question", :as => "main_multiple_question", via: :get
  match "feedback", to: "main#feedback", :as => "feedback", via: :get
  match "feedback_send", to: "main#feedback_send", :as => "feedback_send", via: :post
  match "random_xkcd", to: "main#random_xkcd", :as => "random_xkcd", via: :get
  match "specific_xkcd/:id", to: "main#specific_xkcd", :as => "specific_xkcd", via: :get

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  match '/perf', to: 'perfs#create', via: :post

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:show]
    end
  end

end

app/models/category.rb
# encoding: utf-8

class Category < ActiveRecord::Base
  attr_accessible :text, :title, :ident, :released, :is_root, :answer_ids

  validates :ident, :uniqueness => true, :presence => true
  validates :title, :presence => true

  # i.e. this category has many questions and acts as parent to them
  has_many :questions, :as => :parent
  attr_readonly :questions_count

  has_and_belongs_to_many :answers

  scope :with_questions, where("questions_count > 0")
  scope :without_questions, where(questions_count: 0)
  scope :is_root, where(is_root: true)
  scope :root_categories, where(is_root: true, released: true)

  include DotTools
  include TraversalTools

  before_save do
    Rails.cache.write(:categories_last_update, Time.now)
  end

  def get_root_categories
    return [self] if is_root?
    parent_cats = answers.includes(:question).map { |a| a.get_parent_category }.uniq
    parent_cats.map { |c| c.get_root_categories }.flatten.uniq
  end

  def title_split
    s = title.split(":", 2)
    return s.size == 2 ? s : ["", title]
  end

  def link_text
    "Category #{ident}"
  end

  def trace_to_root(first = false)
    s = ""
    s << " ← C:#{title}" unless first
    return s if is_root?
    s << "\0open\0"
    answers.each do |a|
      s << a.trace_to_root
      s << "\0newline\0"
    end
    s << "\0close\0"
    s
  end

  def dot(active = false)
    id = ident.gsub('"', '')
    id = dot_strike(id) if !released?

    txt = 'K: ' + id
    bg = active ? ', style=filled, fillcolor = "#AAC6D2"' : ''
    %(#{dot_id} [label="#{txt}" #{bg}, shape=#{is_root? ? 'house' : 'folder'}];\n)
  end

  def dot_region
    d = dot(true)
    questions.each do |q|
      d << dot_link_to(self, q)
      d << dot_link_to(q, [q.subquestions, q.subcategories])
    end

    answers.each do |a|
      d << dot_link_from(a, self)
      d << dot_link_from(a.question, a)
    end

    d
  end
end

app/controllers/categories_controller.rb
# encoding: utf-8

class CategoriesController < ApplicationController
  before_filter :require_admin
  before_filter :def_etag, only: [:index, :index_details, :new, :show, :edit, :activate, :deactivate, :suspicious_associations]

  def index
    @categories = Category.with_questions.select([:id, :title])
    @empty = Category.without_questions
  end

  def index_details
    ids = (params[:category_ids] || "").split(",")
    cats = Category.where(id: ids).includes(:answers, :questions => [:parent]).all
    render partial: "index_details", locals: { cats: cats }
  end

  include DefaultActionsHelper

  def new
    @category = Category.new
    @answer = (Answer.find(params['parent']) rescue nil) if params['parent']
    @category.answers << @answer if @answer
  end

  def show
    @category = Category.find(params[:id])
  end

  def listmove
    @categories = Category.with_questions.select([:id, :title, :ident])
  end

  def move
    cats = params[:categories].split('_').map(&:to_i)
    new_cat = params[:new_category]

    ok = true
    @categories = Category.find(cats)
    @categories.each do |cat|
      old_title = cat.title_split
      new_title = (new_cat.empty? ? old_title[1] : (new_cat + ":" + old_title[1]))
      cat.title = new_title
      ok = cat.save && ok
    end
    if ok
      flash[:success] = "Kategorien wurden verschoben."
    else
      flash[:warning] = "Es sind Fehler aufgetreten. Möglicherweise wurden gar keine oder nur einige Sachen verschoben."
    end

    render js: %(window.location.href='categories') and return
  end

  def listactivate
    @categories = Category.with_questions.where(released: false).select([:id, :title, :ident])
  end

  def listdeactivate
    @categories = Category.with_questions.where(released: true).select([:id, :title, :ident])
  end

  def activate
    cats = params[:categories].split('_').map(&:to_i)

    ok = true
    @categories = Category.find(cats)
    @categories.each do |cat|
      cat.released = true
      ok = cat.save && ok
      cat.questions.each do |q|
        q.released = true
        ok = q.save && ok
      end
    end
    if ok
      flash[:success] = "Kategorie und alle direkten Unterfragen wurden freigegeben."
    else
      flash[:warning] = "Es sind Fehler aufgetreten. Möglicherweise wurden gar keine oder nur einige Sachen freigegeben."
    end

    render js: %(window.location.href='categories') and return
  end

  def deactivate
    cats = params[:categories].split('_').map(&:to_i)

    ok = true
    @categories = Category.find(cats)
    @categories.each do |cat|
      cat.released = false
      ok = cat.save && ok
      cat.questions.each do |q|
        q.released = false
        ok = q.save && ok
      end
    end
    if ok
      flash[:success] = "Kategorie und alle direkten Unterfragen wurden gesperrt."
    else
      flash[:warning] = "Es sind Fehler aufgetreten. Möglicherweise wurden gar keine oder nur einige Sachen gesperrt."
    end

    render js: %(window.location.href='categories') and return
  end

  def release
    ok = true
    @category = Category.find(params[:id])
    @category.released = true
    ok = @category.save && ok
    @category.questions.each do |q|
      q.released = true
      ok = q.save && ok
    end
    if ok
      flash[:success] = "Kategorie und alle direkten Unterfragen wurden freigegeben."
    else
      flash[:warning] = "Es sind Fehler aufgetreten. Möglicherweise wurden gar keine oder nur einige Sachen freigegeben."
    end
    redirect_to @category
  end

  def suspicious_associations
    # fcategories and all associated answers (ignoring subquests)
    root_cats = Category.includes(:questions => [:answers])
    root_cats_answers = {}
    root_cats.each do |rc|
      root_cats_answers[rc] = rc.questions.map { |q| q.answers.map(&:id) }.flatten
    end

    # find categories and their parents (answers). Ignoring root questions
    # because they have no parents by definition.
    other_cats = Category.where(is_root: false).includes(:questions => [:answers])
    other_cats_answers = Hash[other_cats.map { |oc| [oc, oc.answer_ids] }]

    # compare against each other to see if any non-root category selects
    # almost all answers of a root category. This makes it obvious if
    # this category should be child to a whole other category.
    @suspicious = []
    other_cats_answers.each do |oc, sel_answ|
      root_cats_answers.each do |rc, avail_answ|
        next if avail_answ.none? || oc == rc
        remain = avail_answ - sel_answ
        ratio = 1.0 - remain.size.to_f / avail_answ.size.to_f
        next if ratio  < 0.7 || ratio == 1.0
        @suspicious << {child: oc, parent: rc, ratio: ratio}
      end
    end
  end
end

app/views/categories/_action_menu.html.erb
<ul class="button-group">
  <li><%=link_to "Bearbeiten", edit_category_path(@category), class: "button"%></li>
  <li><%=link_to "Neue Frage in dieser Kategorie erstellen", new_question_path(:parent => "Category_#{@category.id}"), class: "button"%></li>
  <li><%=link_to "Löschen", @category, method: :delete, confirm: "Es wird nur die Kategorie gelöscht, Fragen hängen ggf. in der Luft.\n\nFortfahren?", class: "button danger"%></li>
</ul>

app/views/categories/_form.html.erb
<p>Wenn diese Kategorie ein neues Themengebiet sein soll, darf kein Eltern-Element angegeben werden. Ansonsten wähle eine Antwort aus, an die diese Kategorie anschließen soll.</p>


<%= form_for(@category) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :ident %>
  <%= f.text_field :ident %>
  <span>Benötigt. Muss eindeutig sein bzgl. aller Kategorien.</span>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <span>Benötigt. Gruppieren z.B. so "Ostasien: Kunstgeschichte"</span>

  <%= f.label :text %>
  <%= f.text_area :text, "data-preview" => "#preview"  %>
  <span>Optional<%=render "latex/help"%></span>
  <div id="preview"><%= render_tex(@category.text) %></div>

  <%= f.label :is_root %>
  <%= f.check_box :is_root, onclick: "$('#parent-selector-wrapper')[this.checked ? 'hide' : 'show']();" %>

  <div id="parent-selector-wrapper" class="clear tex2jax_ignore" style="display: <%=@category.is_root? ? :none : :block%>;">
    <%= f.label :answers, "Eltern-Elem." %>

    <style scoped>
      @import url("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/flick/jquery-ui.min.css");
      .ui-widget{
        font-size:12px;
        line-height: 15px;
      }
      div.option-element:hover {
        color: #fff;
        background: #137DEB;
      }
      select { /* hide select box initially, unless scripts are disabled */
        display: none;
      }
    </style>
    <noscript><style scoped>select { display: block; }</style></noscript>

    <%
      root_cats =  Category.is_root
      # extends the answer table to include the question ident and parent
      # category ID, if available.
      answers = Answer.find_by_sql("SELECT a.id aid, q.ident qident, c.id cid FROM answers a LEFT JOIN questions q ON a.question_id = q.id LEFT JOIN categories c ON q.parent_type = 'Category' AND q.parent_id = c.id")
      selected_answers = @category.answer_ids

      def option_tags(answers, selected)
        # i.e. create text ⇒ id hash
        opts = Hash[ *answers.collect { |a| [ "#{a.qident}/A#{a.aid}", a.aid ] }.flatten ]
        options_for_select(opts, selected)
      end
    %>

    <select id="category_answer_ids" multiple="multiple" name="category[answer_ids][]" style="width: 900px; height: 400px">
      <% root_cats.each do |rc| %>
        <optgroup label="<%=rc.title%>">
          <%=
            here, answers = *answers.partition { |a| a.cid == rc.id }
            option_tags(here, selected_answers)
          %>
        </optgroup>
      <% end %>

      <% if answers.any? %>
        <optgroup label="Antworten, die zu keiner Wurzel-Kategorie gehören (Antworten von Subfragen)">
          <%= option_tags(answers, selected_answers) %>
        </optgroup>

      <% end %>
    </select>

    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <%= javascript_include_tag "jquery.uix.multiselect" %>

    <script>
      $('#category_answer_ids').multiselect();
    </script>
    <br class="clear"/>
    <span>Welche Antworten sollen auf auf diese Kategorie verweisen?</span>
  </div> <!-- # parent-selector-wrapper -->

  <%= f.label :released %>
  <%= f.check_box :released %>
  <% unless @category.new_record? %>
    <span>(<%=link_to "Kategorie + Unterfragen freigeben", release_category_path(@category), confirm: "Dies wird diese Kategorie und alle #{@category.questions.size} direkten Unterfragen freigegeben.\n\nDeine Änderungen werden nicht gespeichert.\nFortfahren?" %>)</span>
  <% end %>


  <%= f.submit @category.new_record? ? "Kategorie anlegen" : "Speichern", class: "button primary big" %>

  <br class="clear"/>
  <br/>
  <%= link_to "Zurück zur Kategorien Liste", categories_path %>
  <% if @answer %>
    <%= link_to "Zurück zur Frage", question_path(@answer.question) %>
  <% end %>
<% end %>

app/views/categories/_index_details.html.erb
<% cats.each do |c| %>
  <div class="alternating <%=cycle("odd", "even")%>">
    <h3>
      <%=link_to "#{c.title} (#{c.ident})", c %>
      <small>
        <%=c.released? ? "freigegeben" : "gesperrt" %>
        <%=trace_to_root_formatter c.trace_to_root(true)%>
      </small>
    </h3>

    <div class="button-group">
      <%= link_to "Details anzeigen", category_path(c), class: "button" %>
      <%= link_to "Bearbeiten", edit_category_path(c), class: "button" %>
      <%= link_to "Neue Frage in #{c.ident}", new_question_path(parent: "Category_#{c.id}"), class: "button" %>
    </div>
    <br/><br/>

    <div class="columnize">
      <% if c.answers.any? %>
        <b>Antworten, die auf diese Kategorie zeigen:</b><br/>
        <% c.answers.each do |a| %>
          <%=link_to a.ident, [a.question, a] %>
        <% end %>
        <br/><br/>
      <% end %>

      <% c.questions.group_by(&:complete?).each do |complete, qs| %>
        <b><%=complete ? "Freigeschaltete Fragen" : "Unfertige Fragen"%>:</b><br/>
        <% qs.each do |q| %>
          <%
            cls = complete ? "" : %|class="strike"|.html_safe
            url = "#{ENV['RAILS_RELATIVE_URL_ROOT']}/admin/questions/#{q.id}"
          %>
          <%# not using helpers because they are slow and there are a lot of links %>
          <a href="<%=url%>" title="<%=q.ident%>" <%=cls%>><%=q.ident%></a>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, "Kategorie bearbeiten #{@category.ident}") %>

<%= render "admin/action_menu" %>

<div>
  <h2>Kategorie bearbeiten: <%=@category.ident%></h2>
  <%=render "form"%>
</div>

app/views/categories/index.html.erb
<% provide(:title, "Kategorienliste") %>

<%= render "admin/action_menu" %>
<div>
  <h2>Kategorienliste</h2>
  <%=link_to "Neue Kategorie anlegen", new_category_path %> |
  <%=link_to "Aktivieren", categories_listactivate_path %> |
  <%=link_to "Deaktivieren", categories_listdeactivate_path %> |
  <%=link_to "Verschieben", categories_listmove_path %> |
  <%=link_to "Kategorien mit möglicherweise fehlenden Verknüpfungen anzeigen", suspicious_associations_path %>
</div>

<% @categories.group_by { |c| c.title.split(":").first }.each do |group_title, cats| %>
  <% reset_cycle %>
  <div>
    <h2><%=group_title%></h2>
    <div class="toggle search-content-urls" style="display: none">
      <div data-content-url="<%=index_details_categories_path(cats.map(&:id).join(","))%>">…lädt…</div>
    </div>
  </div>
<% end  %>

<div>
  <h2>Leere Kategorien</h2>
  <p>Folgende Kategorien enthalten keine Fragen.</p>

  <table id="index2" class="tablesorter">
    <thead>
      <tr><th>Ident</th><th>Title</th><th>Wurzel?</th><th>Aktionen</th></tr>
    </thead>
    <tbody>
      <% @empty.each do |c| %>
        <tr>
          <td><%= link_to(c.ident, c, :class => c.released? ? "" : "strike") %></td>
          <td><%= c.title %></td>
          <td>√<%= c.is_root? %></td>
          <td>
            <%= link_to "Anzeigen", category_path(c) %>
            <%= link_to "Bearbeiten", edit_category_path(c) %>
            <%= link_to "Neue Frage", new_question_path(:parent => "Category_#{c.id}") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/listactivate.html.erb
<% provide(:title, "Kategorie Aktivieren") %>

<%= render "admin/action_menu" %>

<div>

  <h2>Kategorien</h2>
  <div class="toggle clear smallform" id="categories">
    <script>if(hasHash("hide-categories")) $("#categories").hide(); </script>

    <% cache("chooser/#{Category.maximum(:updated_at)}") do %>
    <ul class="inline-chooser" id="categories">
      <%
        groups = @categories.group_by do |c|
          c.title_split[0]
        end.sort_by { |c| c[0] }
      %>

      <% groups.each do |g| %>
        <li>
          <%= content_tag "h3", (g[0].empty? ? "Sonstige" : g[0]) %>
          <div class="toggle" style="display: none"><ul>
            <% g[1].sort { |a, b| a.ident <=> b.ident }.each do |r| %>
              <li>
                <div>
                  <a class="button big toggleable" onclick="$(this).toggleClass('active');" data-id="<%=r.id%>">
                    <%=render_tex r.title_split[1] %>
                  </a>
                </div>
              </li>
            <% end %>
          </ul></div>
        </li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <a class="button huge" id="start-button" onclick="A.activate()" data-confirm="Are you sure?">Aktivieren</a>
</div>

app/views/categories/listdeactivate.html.erb
<% provide(:title, "Kategorie Deaktivieren") %>

<%= render "admin/action_menu" %>

<div>

  <h2>Kategorien</h2>
  <div class="toggle clear smallform" id="categories">
    <script>if(hasHash("hide-categories")) $("#categories").hide(); </script>

    <% cache("chooser/#{Category.maximum(:updated_at)}") do %>
    <ul class="inline-chooser" id="categories">
      <%
        groups = @categories.group_by do |c|
          c.title_split[0]
        end.sort_by { |c| c[0] }
      %>

      <% groups.each do |g| %>
        <li>
          <%= content_tag "h3", (g[0].empty? ? "Sonstige" : g[0]) %>
          <div class="toggle" style="display: none"><ul>
            <% g[1].sort { |a, b| a.ident <=> b.ident }.each do |r| %>
              <li>
                <div>
                  <a class="button big toggleable" onclick="$(this).toggleClass('active');" data-id="<%=r.id%>">
                    <%=render_tex r.title_split[1] %>
                  </a>
                </div>
              </li>
            <% end %>
          </ul></div>
        </li>
      <% end %>
    </ul>
    <% end %>
  </div>
  
  <a class="button huge" id="start-button" onclick="A.deactivate()" data-confirm="Are you sure?">Deaktivieren</a>
</div>

app/views/categories/listmove.html.erb
<% provide(:title, "Kategorie Verschieben") %>

<%= render "admin/action_menu" %>

<div>

  <h2>Kategorien</h2>
  <div class="toggle clear smallform" id="categories">
    <span>Welche Kategorien möchten Sie verschieben?</span>
    <script>if(hasHash("hide-categories")) $("#categories").hide(); </script>

    <% cache("chooser/#{Category.maximum(:updated_at)}") do %>
    <ul class="inline-chooser" id="categories">
      <%
        groups = @categories.group_by do |c|
          c.title_split[0]
        end.sort_by { |c| c[0] }
      %>

      <% groups.each do |g| %>
        <li>
          <%= content_tag "h3", (g[0].empty? ? "Sonstige" : g[0]) %>
          <div class="toggle" style="display: none"><ul>
            <% g[1].sort { |a, b| a.ident <=> b.ident }.each do |r| %>
              <li>
                <div>
                  <a class="button big toggleable" onclick="$(this).toggleClass('active');" data-id="<%=r.id%>">
                    <%=render_tex r.title_split[1] %>
                  </a>
                </div>
              </li>
            <% end %>
          </ul></div>
        </li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <h2>Verschieben Nach</h2>
  <div class="toggle clear" id="categories">
    <%
      groups = @categories.group_by do |c|
        c.title_split[0]
      end.sort_by { |c| c[0] }
      sel_grps = {}
      groups.each do |g|
        n = g[0].empty? ? "Sonstige" : g[0]
        sel_grps[n] = (n == "Sonstige" ? "" : n)
      end
    %>
    <%= label_tag :moveto_category, "Kategorie" %>
    <%= select_tag :moveto_category, options_for_select(sel_grps, :selected => nil) %>
    <span></span>

  </div>
  <br/>
  <a class="button huge" id="start-button" onclick="A.move()" data-confirm="Are you sure?">Verschieben</a>
</div>

app/views/categories/new.html.erb
<% provide(:title, "Neue Kategorie anlegen") %>

<%= render "admin/action_menu" %>

<div>

  <h2>Neue Kategorie</h2>
  <%=render "form"%>
</div>

app/views/categories/show.html.erb
<% provide(:title, "Kategorie #{@category.ident}") %>

<%= render "admin/action_menu"%>

<div>
  <%=render "action_menu"%>

  <h2>Kategorie <%=@category.ident%></h2>
  <%=trace_to_root_formatter @category.trace_to_root(true)%>

  <table>
    <tr><th>Titel</th><td><%=render_tex @category.title%></td></tr>
    <tr><th>Wurzel?</th><td><%=@category.is_root?%></td></tr>
    <tr><th>hat # Fragen</th><td><%=@category.questions.size %></tr>
    <tr><th>Verweise hierher</th><td><%=@category.answers.size %></tr>
    <tr><th>Freigegeben?</th><td><%=@category.released %></tr>
    <tr><th>Text</th><td><%=render_tex @category.text %></tr>
  </table>

</div>

<div>
  <h2>Fragen in dieser Kategorie</h2>
  <% @questions = @category.questions %>
  <%= render "questions/index_table" %>
</div>

<div>
  Hinweis: Nachfolger-Antworten werden in diesem Teilgraph ausgelassen und es wird maximal die zweite Fragenebene angezeigt (d.h. (…) → Kategorie → Frage → Subfrage, aber nicht tiefer).<br/><br/>
  <%=render_dot(@category.dot_region)%>
</div>

app/views/categories/suspicious_associations.html.erb
<% provide(:title, "Möglicherweise fehlende Verknüpfungen") %>

<%= render "admin/action_menu" %>

<div>
  <h2>Möglicherweise fehlende Verknüpfungen</h2>

  <p>Was macht diese Seite? Beispiel: Kategorie Kind wurde ursprünglich mit allen Antworten unter Kategorie Elter verknüpft. Nun haben sich einige Fragen in Elter geändert und daher verweisen nicht mehr alle Antworten aus Eltern nach Kind. Diese Seite listet alle Elter/Kind-Kombinationen auf, deren Verknüpfungen bei 70%+ liegen. Die wahrscheinlichste „Lösung“ ist die Kind-Kategorie zu bearbeiten und alle neu hinzugekommenen Antworten ebenfalls auf die Kind-Kategorie zeigen zu lassen.</p>

  <p>Beachte aber das Subfragen nicht berücksichtigt werden. D.h. wenn alle Subfragen auf eine Kategorie verweisen sollen, wird das hier nicht angezeigt.</p>
</div>

<div>
  <% if @suspicious.any? %>
  <table>
    <tr><th>Kind-Kategorie</th><th>Elter-Kategorie</th><th>Verknüpfungsgrad</th></tr>

    <% @suspicious.each do |s| %>
      <tr>
        <td><%=link_to s[:child].title, edit_category_path(s[:child])%></td>
        <td><%=link_to s[:parent].title, s[:parent]%></td>
        <td><%=[99, (s[:ratio]*100).to_i].min%>%</td>
    <% end %>
  </table>
  <% else %>
    Nichts gefunden.
  <% end %>
</div>