config/routes.rb
Keks::Application.routes.draw do
  resources :password_resets

  match "dot/:sha256.png", to: "dot#simple", :as => "render_dot", :via => :get
  match "preview", to: "latex#complex", :as => "render_preview", :via => :post

  root :to => "main#overview"

  get "main/overview"
  match "hitme", as: "main_hitme", to: "main#hitme"
  match "help", as: "main_help", to: "main#help"

  resources :users, except: :index
  match "users/:id/enrollment" => "users#enroll", as: "enroll_user", via: :post
  match "users/:id/starred" => "users#starred", as: "starred", via: :get
  match "users/:id/history" => "users#history", as: "history", via: :get
  match "questions/:id/star" => "questions#star", as: "star_question", via: :get
  match "questions/:id/unstar" => "questions#unstar", as: "unstar_question", via: :get
  match "questions/:id/perma" => "questions#perma", as: "perma_question", via: :get
  match "stats/:question_id" => "stats#new", as: "new_stat", via: :post

  get "admin/overview"
  scope "/admin" do
    resources :text_storage, only: :update

    match "users", to: "users#index", as: "user_index", via: :get
    match "users/:id/reviews", to: "users#reviews", as: "user_reviews", via: :get
    match "toggle_reviewer/:id", to: "users#toggle_reviewer", as: "user_toggle_reviewer", via: :put
    match "toggle_admin/:id", to: "users#toggle_admin", as: "user_toggle_admin", via: :put

    match "reviews", to: "reviews#messages", as: "reviews", via: :get

    match "reviews/need_attention", to: "reviews#need_attention", as: "need_attention_questions", via: :get

    match "reviews/filter/:filter", to: "reviews#filter", as: "review_filter",via: :get
    match "reviews/find_next/:filter/", to: "reviews#find_next", as: "review_find_next",via: :get
    match "reviews/find_next/:filter/:next", to: "reviews#find_next", as: "review_find_next",via: :get

    resources :questions do
      resources :answers
      resources :hints
      match "toggle_release", to: "questions#toggle_release", as: "toggle_release", via: :put
      match "overwrite_reviews", to: "questions#overwrite_reviews", as: "overwrite_reviews", via: :put
      match "review", to: "reviews#review", as: "review", via: :get
      match "review", to: "reviews#save", as: "review_save", via: :post # new reviews
      match "copy", to: "questions#copy", as: "copy", via: :get
      match "copy_to", to: "questions#copy_to", as: "copy_to", via: :post
      get "list_cat/:category_id", to: "questions#list_cat", on: :collection, as: "list_cat"
      get "select", to: "questions#select", on: :collection, as: "select"
      get :search, on: :collection
    end

    match "single_parent_select", to: "questions#single_parent_select", as: "single_parent_select", via: :get

    resources :categories do
      get "index_details/:category_ids", to: "categories#index_details", on: :collection, as: "index_details"
    end
    match "categories/:id/release", to: "categories#release", :as => "release_category", via: :get
    match "suspicious_assocations", to: "categories#suspicious_associations", :as => "suspicious_associations", via: :get
    match "categories_listmove", to: "categories#listmove", :as => "categories_listmove", via: :get
    match "categories_move", to: "categories#move", :as => "categories_move", via: :get
    match "categories_listactivate", to: "categories#listactivate", :as => "categories_listactivate", via: :get
    match "categories_listdeactivate", to: "categories#listdeactivate", :as => "categories_listdeactivate", via: :get
    match "categories_activate", to: "categories#activate", :as => "categories_activate", via: :get
    match "categories_deactivate", to: "categories#deactivate", :as => "categories_deactivate", via: :get
    match "category_report", to: "stats#category_report", :as => "stat_category_report", via: :get
    match "activity_report", to: "stats#activity_report", :as => "stat_activity_report", via: :get
    match "report/:enrollment_key", to: "stats#report", :as => "stat_report", via: :get

    match "tree", to: "admin#tree", :as => "tree", via: :get
    match "export", to: "admin#export", :as => "export", via: :get
    match "export_question/:question_id", to: "admin#export_question", :as => "export_question", via: :get
  end

  match "main/questions", to: "main#questions", :as => "main_question", via: :get
  match "main/single_question", to: "main#single_question", :as => "main_single_question", via: :get
  match "main/multiple_question", to: "main#multiple_question", :as => "main_multiple_question", via: :get
  match "feedback", to: "main#feedback", :as => "feedback", via: :get
  match "feedback_send", to: "main#feedback_send", :as => "feedback_send", via: :post
  match "random_xkcd", to: "main#random_xkcd", :as => "random_xkcd", via: :get
  match "specific_xkcd/:id", to: "main#specific_xkcd", :as => "specific_xkcd", via: :get

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  match '/perf', to: 'perfs#create', via: :post

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:show]
    end
  end

end

app/controllers/reviews_controller.rb
# encoding: utf-8

class ReviewsController < ApplicationController
  before_filter :require_admin_or_reviewer
  before_filter :require_reviewer, only: :save

  before_filter only: [:review, :save] do get_question(reviews_path) end

  def messages
    @message = TextStorage.find_or_create_by_ident("review_admin_hints")
  end

  def filter
    f = Review.filter(params[:filter])
    @title, @text, @questions = f[:title], f[:text], f[:questions].call(current_user)
    @filter = params[:filter]
  end

  def review
    get_review

  end

  def save
    get_review

    if @review.update_attributes(params[:review])
      flash[:success] = "Review aktualisiert"
      redirect_to question_review_path(@question, filter: params[:filter], next: params[:next])
    else
      flash[:error] = "Review konnte nicht gespeichert werden"
      render 'review'
    end
  end

  def find_next
    pf = params[:filter]
    begin
      f = Review.filter(pf)
    rescue => e # most likely filter doesn’t exist
      flash[:warning] = e.message
      return redirect_to reviews_path
    end


    qqs = f[:questions].call(current_user)
    qqs_ids = qqs.map { |q| q.id.to_s }

    next_list = (params[:next] || "").split(",")

    if qqs.none?
      flash[:notice] = "Keine Reviews mehr nötig bzgl. Filter „#{pf}“"
      return redirect_to reviews_path
    end

    while next_list.any?
      x = next_list.shift
      next unless qqs_ids.include?(x)
      return redirect_to question_review_path(x, filter: pf, next: next_list.join(','))
    end

    flash[:notice] = "Keine Einträge (mehr) in der Review Reihenfolge. Wähle zufälligen Eintrag aus „#{pf}“"
    return redirect_to question_review_path(qqs.sample(1), filter: pf)
  end

  def need_attention
    # admins do not get any lists with questions to review, so no need
    # to calculate those.
    if reviewer?
      @updated = Review.filter(:updated)
      @updated[:questions] = @updated[:questions].call(current_user)

      @need_more_reviews = Review.filter(:need_more_reviews)
      @need_more_reviews[:questions] = @need_more_reviews[:questions].call(current_user)
    end
  end



  private

  def get_review
    @review = Review.find_or_initialize_by_user_id_and_question_id(current_user.id, @question.id)
  end
end

app/views/reviews/_form.html.erb
<div>
  <h2>Mein Review</h2>
  <p>Bitte fasse Dich kurz. Wenn Du Dein Review aktualisierst, landet es an erster Stelle. Entferne daher Anmerkungen, die nicht mehr zutreffen.</p>

  <div class="topright">
  <%=
    (@review.question_updated_since?) \
      ? "Die Frage wurde seit Deiner letzten Aktualisierung geändert"
      : ""
  %>
  </div>

  <%= form_for([@question, @review], method: :post, url: question_review_save_path(@question, filter: params[:filter], next: params[:next])) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :okay %>
    <%= f.check_box :okay %>
    <span>Setze hier nur genau dann ein Häkchen, wenn Du denkst die Frage kann so freigegeben werden.</span>

    <%= f.label :difficulty, "Schwierigkeit" %>
    <div class="slider-box">
      <i>einfach</i>
      <%= f.number_field :difficulty, {"data-slider" => true, "data-slider-range" => "0,1", "data-slider-step" => 0.25, "data-slider-snap" => true, "step" => "any"} %>
      <i>schwer</i>
    </div>

    <%= f.label :learneffect, "Lerneffekt" %>
    <div class="slider-box">
      <i>niedrig</i>
      <%= f.number_field :learneffect, {"data-slider" => true, "data-slider-range" => "0,1", "data-slider-step" => 0.25, "data-slider-snap" => true, "step" => "any"} %>
      <i>hoch</i>
    </div>

    <%= f.label :fun, "Spaß" %>
    <div class="slider-box">
      <i>frustrierend</i>
      <%= f.number_field :fun, {"data-slider" => true, "data-slider-range" => "0,1", "data-slider-step" => 0.25, "data-slider-snap" => true, "step" => "any"} %>
      <i>interessant</i>
    </div>

    <%= f.label :comment %>
    <%= f.text_area :comment, "data-preview" => "#preview"  %>
    <span>Optional<%=render "latex/help"%></span>
    <div id="preview"><%= render_tex(@review.comment) %></div>

    <%= f.submit :class => 'button primary big' %>
  <% end %>
</div>

app/views/reviews/_generic_question_list.html.erb
<%
  limit ||= nil

  cats = {}
  questions.each_with_index do |q, ind|
    roots = q.get_root_categories
    roots.each do |r|
      cats[r] ||= []
      cats[r] << q
    end

    if limit && params[:nolimit] != "1" && ind >= limit-1
      %>
        <b>Hinweis:</b>
        Zeige nur <%=limit%> von <%=questions.size%> Fragen, damit die Seite schnell bleibt.
        <%=link_to "Alles anzeigen (legt Seite lahm, sparsam nutzen)", "?nolimit=1"%>
      <%
      break
    end
  end
%>

<ul>
  <% cats.keys.sort { |c1, c2| c1.ident <=> c2.ident }.each do |cat| %>
    <% quests = cats[cat] %>
    <% in_queue = quests.map { |q| q.id.to_s } %>
    <li><h4 style="margin: 10px 0"><%=cat.title%></h4>
      <div class="toggle" style="display: none"><ul>
      <% quests.each do |q| %>
        <% in_queue.shift %>
        <li><%=link_to q.ident, question_review_path(q, filter: filter, next: in_queue.join(',')) %></li>
      <% end %>
      </ul></div>
    </li>
  <% end %>
</ul>

app/views/reviews/_menu.html.erb
<div class="box submenu">
  <ul>
    <li>Reviews:</li>
    <li><%= link_to "Mitteilungen", reviews_path, class: 'primary' %></li>
    <li><%= link_to "Fragen die Deine Aufmerksamkeit benötigen", need_attention_questions_path, class: 'primary' %></li>
    <li><%= link_to "Meine Reviews", user_reviews_path(current_user), class: '' %></li>
  </ul>

  <ul>
    <li>Filtern:</li>
    <% Review.get_filters.each do |f| %>
      <% next if Review.filter(f)[:hide_in_menu] %>
      <li><%= link_to Review.filter(f)[:link_title], review_filter_path(f) %></li>
    <% end %>
  </ul>
</div>

app/views/reviews/_okay_state.html.erb
<div class="okay-state alert-<%=okay ? "success" : "error" %>">
  <% if okay %>
    ✓
  <% else %>
    ✗
  <% end %>
</div>

app/views/reviews/_show.html.erb
<%
dimmed = question_updated_since? unless defined?(dimmed)
if dimmed
%>
<div style="opacity: 0.7">
<% end %>

<div style="width: 25%; float:left">
  <%= render "reviews/okay_state", okay: review.okay %>

  <table style="margin-top: 0; float: left">
    <tr><th>Schwierigkeit:</th><td><meter value="<%=review.difficulty%>"></meter></td></tr>
    <tr><th>Lerneffekt:</th><td><meter value="<%=review.learneffect%>"></meter></td></tr>
    <tr><th>Spaß:</th><td><meter value="<%=review.fun%>"></meter></td></tr>
  </table>
</div>

<div style="float:left; width: 70%">
  <em>
  <strong><%=review.user.nick %></strong>
  <% if admin? %>
    (<%= link_to "Reviews anzeigen", user_reviews_path(review.user) %>)
  <% end %>
  (vor <%= time_ago_in_words(review.updated_at) %>)

  </em>
  <br/>

  <%= render_tex review.comment %>
</div>

<hr class="clear"/>

<% if dimmed %>
</div>
<% end %>

app/views/reviews/filter.html.erb
<%= render "menu"  %>

<div>
  <h3><%=@title%></h3>
  <p><%=@text%></p>
  <%= render "generic_question_list", questions: @questions, filter: @filter %>
</div>

app/views/reviews/messages.html.erb
<% provide(:title, "Mitteilungen") %>

<%= render "menu"  %>

<div>
  <h2>Wichtige Mitteilungen aus dem Controlling</h2>

  <%= render_tex(@message.value) %>
</div>

<% if admin? %>
  <div>
  <%= form_for(@message) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :ident %>

    Nimm Rücksicht auf andere, fasse Dich kurz!<br class="clear"/>
    <%= f.text_area :value, "data-preview" => "#preview"  %>
    <span><%=render "latex/help"%></span>
    <div id="preview"><%= render_tex(@message.value) %></div>

    <%= f.submit "Mitteilung speichern", class: "button primary big" %>
  <% end %>
  </div>
<% end %>

app/views/reviews/need_attention.html.erb
<% provide(:title, "Fragen, die Deine Aufmerksamkeit benötigen") %>

<%= render "menu"  %>

<% if admin? %>
<div>
  Lieber Admin, am ehesten interessieren Dich die Auflistungen <%= link_to "Fragen mit „nicht okay“", review_filter_path(:not_okay) %> (kaputte Fragen) und <%= link_to "#{REVIEW_MIN_REQUIRED_REVIEWS}+ okay, 0 nicht-okay", review_filter_path(:enough_good_reviews) %> (freischaltbare Fragen).
</div>
<% end %>


<% if reviewer? %>
  <div>
    Lieber Reviewer, nachfolgend findest Du eine Auflistung von Fragen, die am wahrscheinlichsten Deiner Aufmerksamkeit bedürfen. Kommt im Anschluss nichts, gibt’s wohl nichts zu tun. Im Menü oben kannst Du auch nach anderen Sachen filtern.
  </div>

  <% qqs = @updated[:questions] %>
  <% if qqs.any? %>
    <% in_queue = qqs.map { |q| q.id.to_s } %>
    <div>
      <h3><%=@updated[:title]%></h3>
      <p><%=@updated[:text]%></p>
      <ul>
        <% qqs.each do |q| %>
          <% in_queue.shift %>
          <li><%=link_to "#{q.ident} (Frage vor #{time_ago_in_words q.updated_at} geändert)", question_review_path(q, filter: "updated", next: in_queue.join(',')) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% qqs = @need_more_reviews[:questions] %>
  <% if qqs %>
    <div>
      <h3>Fragen, die ein Review brauchen</h3>
      <p>Nachfolgende Fragen haben bisher zu wenig Reviews erhalten. Du hast diese Fragen noch nie reviewt.</p>
      <%= render "generic_question_list", questions: qqs, limit: 50, filter: "need_more_reviews" %>
    </div>
  <% end %>
<% end # is reviewer? %>

app/views/reviews/no_reviews.html.erb
<div>
  <%= render "menu"  %><br/><br/>

  <h3>Keine Reviews</h3>
  <p>Folgende Fragen haben genau null Reviews.</p>

  <%= render "generic_question_list", questions: @questions %>
</div>

app/views/reviews/overview.html.erb
<% provide(:title, "Nutzerübersicht") %>

<% if admin? %>
<div>
  <%= render "menu"  %><br/><br/>

  Lieber Admin, am ehesten interessieren Dich die Auflistungen <%= link_to "Fragen mit „nicht okay“", not_okay_questions_path %> (kaputte Fragen) und <%= link_to "#{REVIEW_MIN_REQUIRED_REVIEWS}+ okay, 0 nicht-okay", enough_good_reviews_questions_path %> (freischaltbare Fragen).
</div>
<% end %>


<% if reviewer? %>
  <div>
    <%= render "menu"  %><br/><br/>

    Lieber Reviewer, nachfolgend findest Du eine Auflistung von Fragen, die am wahrscheinlichsten Deiner Aufmerksamkeit bedürfen. Kommt im Anschluss nichts, gibt’s wohl nichts zu tun. Im Menü oben kannst Du auch nach anderen Sachen filtern.
  </div>

  <% if @reviews_need_update.any? %>
    <div>
      <h3>Seit Deinem letztem Review aktualisiert</h3>
      <p>Du hast diese Fragen bereits einmal reviewed. Die Frage wurde jedoch aktualisiert seitdem Du das getan hast. Bitte prüfe ob Deine Anmerkungen noch stimmen und ändere ggf. Deine Einstellungen.</p>
      <ul>
        <% @reviews_need_update.each do |r| %>
          <% q = r.question %>
          <li><%=link_to "#{q.ident} (Frage vor #{time_ago_in_words q.updated_at} geändert)", question_review_path(q) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @questions_need_review %>
    <div>
      <h3>Fragen, die ein Review brauchen</h3>
      <p>Nachfolgende Fragen haben bisher zu wenig Reviews erhalten. Du hast diese Fragen noch nie reviewt.</p>
      <%= render "generic_question_list", questions: @questions_need_review, limit: 50 %>
    </div>
  <% end %>

<% end # is reviewer? %>

app/views/reviews/review.html.erb
<% provide(:title, "Frage reviewen") %>

<%= render "menu"  %>

<% filter = Review.filter(params[:filter]) rescue nil %>
<% if filter %>
  <div>
    <%=link_to "Nächste Frage (in „#{filter[:link_title]}“)", review_find_next_path(filter: params[:filter], next: params[:next] || "") %>
  </div>
<% end %>


<div>
  <h2>Frage <%=@question.ident%></h2>
  <%=trace_to_root_formatter @question.trace_to_root(true)%>
  <span style="color: #777;display: block;margin-top:-10px;margin-bottom: 20px">
    Fragentyp: <%= @question.difficulty(:name) %> |
    Studiengang: <%= x=@question.study_path(:name); x.blank? ? "alle" : x %> |
    Freigegeben: <%=bool_to_symbol(@question.released?)%> |
    <span title="<%=@question.incomplete_reason || "alles ok"%>" style="cursor: help">
      für Studis sichtbar: <%=bool_to_symbol(@question.complete?)%>
    </span>
  </span>

  <div class="topright">
    <%=link_to "Frage „live“ ansehen", "#{main_hitme_path}#hide-options#question=#{@question.id}" %>
    <% if admin? %>
      | <%= render "questions/toggle_release" %>
      | <%= link_to("Bearbeiten", edit_question_path(@question)) %>
    <% end %>
  </div>

  <%= render "questions/render_review", question: @question %>
</div>

<div>
  <h2>Reviews</h2>
  <% if @question.reviews.none? %>
    bisher noch keine.
  <% else %>
    <%
      any_not_okay = @question.reviews.any? { |r| !r.okay }
      any_unread = @question.reviews.any? { |r| r.question_updated_since? }

      if admin? && (any_not_okay || any_unread)
        confirm = ["Wenn Du fortfährst, passiert folgendes:"]
        if any_not_okay
          confirm << "• nicht-okay-e Reviews, kriegen einen grünen Haken"
          confirm << "• bei den umgestellten Reviews wird Dein Tun vermerkt"
        end
        confirm << "• die Frage wird für alle Reviewer als gelesen markiert"
        confirm += ["", "Fortfahren und Reviews ignorieren?"]
        %>
        <%=link_to "Ich habe Recht™ und die Reviews sind mir egal",
          question_overwrite_reviews_path(@question),
          confirm: confirm*"\n",
          method: :put
        %>
        <hr class="clear"/>
        <%
      end
    %>

    <% question_edit_msg_shown = false %>
    <% @question.reviews.each do |r| %>
      <% if !question_edit_msg_shown && r.question_updated_since? %>
        <%= render "last_update" %>
        <% question_edit_msg_shown = true %>
      <% end %>

      <%= render "show", review: r, dimmed: question_edit_msg_shown %>
    <% end %>

    <%= render "last_update" if !question_edit_msg_shown %>
  <% end %>
</div>


<% if reviewer? %>
  <%= render "form" %>
<% end %>


<div>
  <h2>Graph</h2>
  <p>Zur leichteren Orientierung wo diese Frage anzusiedeln ist findest Du nachfolgend einen Baum-Graphen, der einen Auschnitt zeigt. „Höhere“ Sachen sind links „tiefere“ rechts. D.h. wenn man den ganzen Graph darstellen würde, wären ganz links die auf der Startseite auswählbaren Kategorien.</p>

  <%=render_dot(@question.dot_region(true))%>
</div>